// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAjsTxGEjt1d2oUg2eNdLHapWjcC-fsLU',
    appId: '1:195990839533:web:93e7d91bd70e11fc13ace4',
    messagingSenderId: '195990839533',
    projectId: 'technischerdienst-aea86',
    authDomain: 'technischerdienst-aea86.firebaseapp.com',
    storageBucket: 'technischerdienst-aea86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo1oGC6efp1GGrkMq_gRTlrofLprcZT6M',
    appId: '1:195990839533:android:b79348c87c8edd7d13ace4',
    messagingSenderId: '195990839533',
    projectId: 'technischerdienst-aea86',
    storageBucket: 'technischerdienst-aea86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPZxX7kPZ3M5jozVvo07-ftMeJl3pmOig',
    appId: '1:195990839533:ios:bcdaa81a2c1b9ab313ace4',
    messagingSenderId: '195990839533',
    projectId: 'technischerdienst-aea86',
    storageBucket: 'technischerdienst-aea86.appspot.com',
    iosBundleId: 'com.example.technischerDienst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPZxX7kPZ3M5jozVvo07-ftMeJl3pmOig',
    appId: '1:195990839533:ios:286ae0b84d83e35613ace4',
    messagingSenderId: '195990839533',
    projectId: 'technischerdienst-aea86',
    storageBucket: 'technischerdienst-aea86.appspot.com',
    iosBundleId: 'com.example.technischerDienst.RunnerTests',
  );
}
